# Generated by Django 3.0.2 on 2020-02-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_auto_20200210_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouserrelation',
            name='preference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
