# Generated by Django 3.0.2 on 2020-02-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_videouserrelation_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videouserrelation',
            name='preference',
        ),
    ]
