# Generated by Django 3.0.3 on 2020-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_remove_videouserrelation_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='liker',
        ),
        migrations.DeleteModel(
            name='VideoUserRelation',
        ),
    ]
